<?php

declare(strict_types=1);

/** Regenerate command-help documentation and verify it in CI. */
$root = dirname(__DIR__);
$check = in_array('--check', $argv, true);
$commands = ['new', 'package', 'web'];
$sources = ['bin/laravel', 'src/NewCommand.php', 'src/PackageCommand.php', 'src/WebCommand.php', 'src/Web/router.php', 'src/Agent.php', 'src/Concerns/InstallsUiPresets.php'];
$lines = ['# Command reference', '', '<!-- Generated by scripts/sync-docs.php. Do not edit directly. -->', '', 'This is exact CLI help from this checkout. Run `composer docs:update` after command changes.'];
foreach ($commands as $command) {
    $process = proc_open([PHP_BINARY, 'bin/laravel', $command, '--help', '--no-ansi'], [1 => ['pipe', 'w'], 2 => ['pipe', 'w']], $pipes, $root);
    if (! is_resource($process)) { fwrite(STDERR, "Unable to read {$command} help.\n"); exit(1); }
    $output = stream_get_contents($pipes[1]); $error = stream_get_contents($pipes[2]); fclose($pipes[1]); fclose($pipes[2]);
    if (proc_close($process) !== 0) { fwrite(STDERR, $error); exit(1); }
    $lines = [...$lines, '', '## `laravel '.$command.'`', '', '```text', rtrim($output), '```'];
}
$manifest = [];
foreach ($sources as $source) {
    $path = $root.DIRECTORY_SEPARATOR.$source;
    if (! file_exists($path)) { fwrite(STDERR, "Missing documentation source: {$source}\n"); exit(1); }
    // Normalize line endings so Windows (CRLF) and CI (LF) checkouts produce identical hashes...
    $manifest[$source] = hash('sha256', str_replace("\r\n", "\n", (string) file_get_contents($path)));
}
$files = ['docs/reference/command-help.md' => implode(PHP_EOL, $lines).PHP_EOL, 'docs/reference/source-manifest.json' => json_encode($manifest, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES).PHP_EOL];
$stale = [];
// Compare with normalized line endings so autocrlf checkouts don't read as drift...
$normalize = fn (string $contents): string => str_replace("\r\n", "\n", $contents);
foreach ($files as $file => $contents) {
    $path = $root.DIRECTORY_SEPARATOR.$file;
    if (! file_exists($path) || $normalize((string) file_get_contents($path)) !== $normalize($contents)) { $stale[] = $file; if (! $check) { is_dir(dirname($path)) || mkdir(dirname($path), 0777, true); file_put_contents($path, $contents); } }
}
if ($check && $stale !== []) { fwrite(STDERR, "Generated documentation is stale:\n - ".implode("\n - ", $stale)."\nRun composer docs:update.\n"); exit(1); }
echo $stale === [] ? "Documentation is up to date.\n" : "Documentation updated:\n - ".implode("\n - ", $stale)."\n";